parameters:
    fs_core.entity.user.class: FS\Bundle\CoreBundle\Entity\User
    fs_core.repository.user.class: FS\Bundle\CoreBundle\Repository\UserRepository
    fs_core.entity.survey.class: FS\Bundle\CoreBundle\Entity\Survey
    fs_core.repository.survey.class: FS\Bundle\CoreBundle\Repository\SurveyRepository
services:
    fs_core.repository.user:
        class: %fs_core.repository.user.class%
        arguments: [%fs_core.entity.user.class%]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    fs_core.repository.survey:
        class: %fs_core.repository.survey.class%
        arguments: [%fs_core.entity.survey.class%]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository