parameters:
#    fs_core.example.class: FS\Bundle\CoreBundle\Example

services:
#    fs_core.example:
#        class: %fs_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
